var i18 = {
'_ui_lock_msg':'You telephone will be locked with the following password:',
'_ui_help':'Help',
'_ui_lock_disabled':'Currently remote locking is not enabled on your phone. Open Bandog app on your phone and press enable lock button',
'signout':'Sign out',
'show_location':'Location',
'lock_phone':'Lock phone',
'_ui_latitude':'latitude',
'last_time_lock_pass':'Last time you locked your phone with this password',
'play_alarm':'Alarm',
'please_signin':'Please Sign In',
'_ui_updatetime':'update time',
'loading':'Loading...',
'_ui_accuracy':'accuracy',
'_ui_signin':'Please Sign in',
'send_alarm':'Send alarm',
'lock_send':'Lock',
'_ui_longitude':'longitude',
'_ui_location_disabled':'Location sharing is not enabled on your phone. Open Bandog app on your phone and press enable location button',
'_ui_signout':'Sign out',
'':''}
