var i18 = {
'_ui_device_not_registered_text':'You need to install Bandog Messenger app on your android phone and press \'Register\' button',
'messages_viewed':'Old messages',
'_history_header':'History',
'_ui_nw_rcpt_label':'Recipients',
'_ui_send_btn':'Send message',
'goto_bookmark':'Finish him!',
'_ui_no_contacts_math_filtering':'no matches',
'_ui_loading':'Loading... please wait',
'incoming':'Incoming',
'compose':'Compose',
'outgoing':'History',
'_ui_header':'Bandog Messenger (beta)',
'contact_details':'Contact Details',
'_ui_device_not_registered_header':'Your phone isn\'t registered',
'name':'Bandog Messenger',
'description':'One ring to rule them all',
'_ui_contacts_header':'Contacts',
'messages_history':'Messages History',
'_ui_nw_text_label':'Message text',
'':''}
